// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fslfgjyyizmrnzqntlaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzbGZnanl5aXptcm56cW50bGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjgyNjksImV4cCI6MjA2NTU0NDI2OX0.QiH0wZOv54YwV6goR5Krd3Lv40A1HSbbsQ395fIUpkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);